### ISSUE TITLE
Mambo not detected in Bluetooth in both Linux and Windows 

### ISSUE THREAD

**Issue by ghost** [parrot-opensource/mambo-opensource#1]
I am trying to connect the Parrot Mambo drone to the Debian Linux operating system. I have powered on the drone with the battery connected.
I run the following command on Terminal to scan for all bluetooth devices
_sudo hcitool scan_

But the scan is **not able to detect** the drone.

I tried doing the same in Windows 10. I am using ABE Bluetooth Dongle for this purpose. Even there it is **not able to detect** the drone. 

Any idea what needs to be done so that the drone turns up on scan on both Linux and Windows?

P.S. - I tried the same on Parrot Rolling Spider Drone. And I could see the drone **being detected** on both Linux and Windows 10.

**Comment by ghost** [comment]
I figured it out. The reason I am able to do this for Rolling Spider is because Parrot has provided a custom firmware for it which enables bluetooth connection to PC while the normal firmware does not.
So if we want to do the same for Mambo , we need a customized firmware for Mambo that would allow BLE connection to PCs

**Comment by keonyi** [comment]
Did you find 'customized firmware for Mambo '?
I also interisted in.

**Comment by GoldenPhoenix15** [comment]
can you explain in detail please?
i'm not able to connect the drone to windows.
